// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSDUR2WellsConnector.Models;

namespace OSDUR2WellConnector.Migrations
{
    [DbContext(typeof(WellDbContext))]
    [Migration("20200716214615_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("OSDUR2WellsConnector.Models.Well", b =>
                {
                    b.Property<string>("UWI")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceOrganisationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVerticalMeasurementID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime()");

                    b.Property<string>("Lat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lon")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingEnvironmentID")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuadrantID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceSecurityClassification")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceTypeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpudDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateProvinceID")
                        .HasColumnType("TEXT");

                    b.Property<string>("WellName")
                        .HasColumnType("TEXT");

                    b.HasKey("UWI");

                    b.ToTable("Wells");
                });
#pragma warning restore 612, 618
        }
    }
}
